name: Build parent artifact

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

jobs:
  build-artifact:
    name: Build Borealis parent artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build artifact
        run: ./mvnw -B clean package

      - name: Run Snyk code analysis
        run: ./mvnw -B snyk:test snyk:monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload vulnerability scan result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Test building sample project
        run: ./mvnw -B -f sample-project/pom.xml clean package

      - name: Run Snyk code analysis on sample project
        run: ./mvnw -B -f sample-project/pom.xml snyk:test snyk:monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
