name: Build parent project

on:
  push:
  pull_request:

jobs:
  build-project:
    name: Build Borealis parent project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build parent project artifact
        run: ./mvnw -B clean verify

      - name: Verify sample project
        run: ./mvnw -B -f sample-project/pom.xml clean verify

      - name: Check for vulnerabilities on sample project
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --file=sample-project/pom.xml

      - name: Upload vulnerability scan result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
