name: Build parent project

on:
  push:
  pull_request:

jobs:
  build-project:
    name: Build Borealis parent project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build parent project artifact
        run: ./mvnw -B clean verify
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload vulnerability scan result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Verify sample project
        run: ./mvnw -B -f sample-project/pom.xml clean verify
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
