name: Build parent artifact

on:
  push:
    branches-ignore:
      - 'dependabot/**'
      - main
  pull_request:

jobs:
  build-artifact:
    name: Build Borealis parent artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3.5.1
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build artifact
        run: ./mvnw -B clean verify
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
