name: Build parent artifact

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
  workflow_call:

jobs:
  build-artifact:
    name: Build Borealis parent artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build artifact
        run: ./mvnw -B clean package

      - name: Test building sample project
        run: ./mvnw -B -f sample-project/pom.xml clean package

  check-vulnerabilities:
    name: Check vulnerabilities with Snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload vulnerability scan result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
