name: Delete release branch

on:
  release:
    types: [ published ]


jobs:
  delete-branch:
    name: Delete release branch release/${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Delete branch
        run: |
          if git rev-parse --quiet --verify release/${{ github.ref_name }} > /dev/null; then
            git push origin -d release/${{ github.ref_name }}
          fi
