name: Prepare new version release

on:
  push:
    branches:
      - 'main'

jobs:
  prepare-release:
    name: Prepare Borealis parent artifact release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
          server-id: github

      - name: View settings.xml
        run: cat /home/runner/.m2/settings.xml

      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Prepare artifact release
        run: ./mvnw -B release:prepare
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # TODO Create pre-release page in GitHub
