name: Prepare new version release

on:
  workflow_dispatch:
    inputs:
      bumpVersion:
        description: 'Version to bump'
        required: true
        default: 'Incremental'
        type: choice
        options:
        - Major
        - Minor
        - Incremental

jobs:
  prepare-release:
    name: Prepare Borealis parent artifact release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
          server-id: github

      - name: View settings.xml
        run: cat /home/runner/.m2/settings.xml

      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          
      - name: Generate release and development version numbers
        id: generate-versions
        run: |
          echo "::set-output name=release::1.0.0" #TODO Update based on input
          echo "::set-output name=development::1.0.1" #TODO Update based on input

      - name: Prepare artifact release
        run: |
          ./mvnw -B release:prepare \
          -DreleaseVersion=${{ steps.generate-versions.outputs.release }} \
          -DdevelopmentVersion=${{ steps.generate-versions.outputs.development }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
