name: Prepare non-major version release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to prepare'
        required: true
        type: string

jobs:
  prepare-release:
    name: Prepare Borealis parent artifact release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          ref: release/v${{ inputs.version }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3.5.1
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
          server-id: github

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Configure Git
        run: |
          git config user.email "ecristobalr@gmail.com"
          git config user.name "ecristobal"
          git config user.signingkey 2AC107259C09A885
          git config commit.gpgsign true
          git config tag.gpgSign true

      - name: Generate release version number
        id: generate-versions
        run: |
          CURRENT_VERSION=$(./mvnw build-helper:parse-version help:evaluate -Dexpression=project.version -q -DforceStdout)
          RELEASE_VERSION=${CURRENT_VERSION%"-SNAPSHOT"}
          echo "release-version=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Prepare artifact release
        run: |
          ./mvnw -B release:prepare release:clean \
          -DreleaseVersion=${{ steps.generate-versions.outputs.release }} \
          -DupdateWorkingCopyVersions=false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Push release/v${{ inputs.version }} branch
        run: git push origin release/v${{ inputs.version }} --force

      - name: Push tag v${{ env.release-version }}
        run: git push origin v${{ env.release-version }}

      - name: Create release draft in Github
        uses: ncipollo/release-action@v1
        with:
          draft: true
          tag: v${{ env.release-version }}
          generateReleaseNotes: true
