name: Release parent artifact

on:
  release:
    types: [ published ]

jobs:
  release-artifact:
    name: Release Borealis parent artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build & Deploy artifact
        run: ./mvnw -B deploy
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  delete-old-versions:
    needs: release-artifact
    name: Delete old artifact versions from artifact repository
    runs-on: ubuntu-latest
    steps:
      - name: Remove old artifact versions
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'es.borealis.daycare.center.borealis-parent'
          min-versions-to-keep: 2
